### PR TITLE
Update blst to v0.3.7

### PR DESCRIPTION
**Pull request by zilm13**
Sorry for taking this, I realized what's this task about only after digging in. As your PR is merged, patch could be removed. I'm not sure how to test this properly, it compiles locally on my system but I've not tried to make full jar and align it with Teku.

### CODE REVIEW

**Comment by zilm13** [comment]
Run Teku bls tests with assemble artifact, works ok on Linux

**Review by ajsutton — APPROVED** [review]
LGTM.

**Comment by zilm13** [comment]
@ajsutton could you make a release, please

**Comment by ajsutton** [comment]
Release is done.

**Pull request merged**
